### ISSUE TITLE
Link checking doesn't check the fragment identifier

### ISSUE THREAD

**Issue by peterhartman** [LukasHechenberger/broken-link-checker-local#2]
I opened this against BLC but perhaps it belongs here as it is easier to address for static sites:
https://github.com/stevenvachon/broken-link-checker/issues/108

**Comment by LukasHechenberger** [comment]
Well, the only possibility i see to fix this is to validate the crawled html pages have a corresponding `<a>` element. HTML parsing and handling is done inside *blc*, therefore I'd say it should be implemented there. To implement this in the *blcl* package would duplicate much of the work done inside *blc*. You may fork it and provide a fix, once it is merged, I'll update the dependency in this package.
