### ISSUE TITLE
Would be great to have a --baseURL option for the served files

### ISSUE THREAD

**Issue by peterhartman** [LukasHechenberger/broken-link-checker-local#4]
My static site has a baseURL at which it is served, currently I have to build a separate set of static files with / as the baseURL to allow blcl to work.

It would be great if I could supply --baseURL to blcl so that it would serve from this root and I can avoid the double build

**Comment by LukasHechenberger** [comment]
Implemented. Could you check out if it works for you with `0.2.0-beta.0`?
Install it using `npm install -g broken-link-checker-local@beta`

**Comment by peterhartman** [comment]
Works perfectly thank you!

**Comment by LukasHechenberger** [comment]
Okay, thanks, I'll merge it to master.

**Comment by LukasHechenberger** [comment]
Now available in v0.2.0
