### ISSUE TITLE
is there a way to check for all files in directory? 

### ISSUE THREAD

**Issue by matkoniecz** [LukasHechenberger/broken-link-checker-local#49]
I have a https://mapsaregreat.com/laser/ page not linked from other parts of the site (what is another mistake which should be fixed)

It has some dead links that will not be found by `blcl -ro . --filter-level 3` on the main website

Is there some way to avoid this kind of problem (or another tool to detect such unlinked pages)?

**Comment by LukasHechenberger** [comment]
I'm not sure if i unterstand what you mean: This tool was developed to detect broken links, not if all pages link to each other. It's not necessarily an issue if pages are only available via their exact url. In some cases this is exactly what you want, e.g. for google search console verification pages (See https://support.google.com/webmasters/answer/9008080?hl=en).
I don't really see the benefit of this functionality, but maybe you can explain your use case to me.

**Comment by matkoniecz** [comment]
I have a folder with website with files

* `index.html` linking `linked.html`
* `linked.html`
* `without_link.html`

This tool when invoked with `blcl -ro . --filter-level 3` will check `index.html` and `linked.html`

`without_link.html` will not be checked, and I want to check also this one.

Checking each html file with separate call of `blcl` is unfeasible, as there is no way to skip valid links so broken ones will be lost in noise.

Though maybe script calling `blcl` individually for each file and grepping output would be feasible?

**Comment by LukasHechenberger** [comment]
I see, that's a very special use case. I use this module mostly for CI tests, where I call *blcl* for all "entry points" of a website. In most cases this is just the landing page, so it's `blcl -r https://example.com`. If a broken link is detected the script fails and I look through the output to find out what's wrong. Normally I do this manually, but a `... | grep 'BROKEN'` should do the trick:

```
npx broken-link-checker-local https://mapsaregreat.com/laser/ | grep 'BROKEN'
├─BROKEN─ https://mapsaregreat.com/laser/articles.html (HTTP_404)
├─BROKEN─ https://mapsaregreat.com/laser/svg (HTTP_404)
```

**Comment by matkoniecz** [comment]
> that's a very special use case

And feel free to WONTFIX it! Right now this tool is the most useful one of what I found, so thanks again for publishing it!
